SELECT
    c.CAR_ID,
    c.CAR_TYPE,
    CAST((c.DAILY_FEE * (100 -p.DISCOUNT_RATE) / 100) AS SIGNED) * 30 AS FEE
FROM (SELECT H.CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
      GROUP BY H.CAR_ID
      HAVING MAX(H.END_DATE) <= '2022-11-01'
      ) AS h
JOIN CAR_RENTAL_COMPANY_CAR c ON h.CAR_ID = c.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p ON c.CAR_TYPE = p.CAR_TYPE
WHERE 
    (c.CAR_TYPE = '세단' OR c.CAR_TYPE = 'SUV')
AND (p.DURATION_TYPE = '30일 이상')
AND ((c.DAILY_FEE * (100 -p.DISCOUNT_RATE) / 100) * 30 >= 500000 AND (c.DAILY_FEE * (100 -p.DISCOUNT_RATE) / 100) * 30 < 2000000)
ORDER BY FEE DESC, c.CAR_TYPE ASC, c.CAR_ID  ASC

#SELECT
#*
#FROM (SELECT H.CAR_ID
#      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
#      GROUP BY H.CAR_ID
#      HAVING MAX(H.END_DATE) <= '2022-11-01'
#      ) AS h
#JOIN CAR_RENTAL_COMPANY_CAR c ON h.CAR_ID = c.CAR_ID
##JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p ON c.CAR_TYPE = p.CAR_TYPE #AND(h.CAR_ID = c.CAR_ID)
#WHERE 
#    (c.CAR_TYPE = '세단' OR c.CAR_TYPE = 'SUV')
##AND (h.END_DATE <= '2022-11-01')
##AND (p.DURATION_TYPE = '30일 이상')