SELECT
    YEAR(s.SALES_DATE) AS YEAR,
    MONTH(s.SALES_DATE) AS MONTH,
    COUNT(DISTINCT s.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT s.USER_ID) / total_2021,1) AS PUCHASED_RATIO
FROM 
    (
        SELECT *,  COUNT(*) OVER () AS total_2021
        FROM USER_INFO u
        WHERE YEAR(u.JOINED) = 2021
    ) AS u
JOIN ONLINE_SALE s on u.USER_ID = s.USER_ID
GROUP BY YEAR(s.SALES_DATE), MONTH(s.SALES_DATE)
ORDER BY YEAR(s.SALES_DATE), MONTH(s.SALES_DATE);
# 서브쿼리를 줄임