SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    SUM(p.price * o.AMOUNT) AS TOTAL_SALES
FROM FOOD_ORDER o
JOIN FOOD_PRODUCT p ON o.PRODUCT_ID = p.PRODUCT_ID
WHERE o.PRODUCE_DATE >= '2022-05-01' AND o.PRODUCE_DATE < '2022-06-01'
GROUP BY p.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, p.PRODUCT_ID ASC;