SELECT f.FLAVOR
FROM FIRST_HALF f
JOIN
    (
        SELECT j.FLAVOR, SUM(j.TOTAL_ORDER) AS TOTAL_ORDER
        FROM JULY j
        GROUP BY j.FLAVOR
    ) j ON f.FLAVOR = j.FLAVOR
ORDER BY (f.TOTAL_ORDER + j.TOTAL_ORDER) DESC
LIMIT 3
;