SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
# IN으로 둘다 맞는지 비교한다.
# GROUP BY에 쓰지 않은 컬럼을 SELECT에 쓰면 정말 아무거나 하나만 띡 갖다 던져준다.
WHERE (CATEGORY, PRICE) IN (
    SELECT CATEGORY, MAX(PRICE)
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
)
ORDER BY MAX_PRICE DESC
;