SELECT
    p.CATEGORY,
    b.MAX_PRICE,
    p.PRODUCT_NAME
FROM FOOD_PRODUCT p
JOIN (SELECT
    p.CATEGORY,
    MAX(p.PRICE) AS MAX_PRICE,
    p.PRODUCT_NAME
FROM FOOD_PRODUCT p
GROUP BY p.CATEGORY
HAVING p.CATEGORY IN ('과자','국','김치','식용유')
     ) AS b
ON p.CATEGORY = b.CATEGORY AND p.PRICE = b.MAX_PRICE
ORDER BY b.MAX_PRICE DESC
;

#SELECT
#    p.CATEGORY,
#    MAX(p.PRICE) AS MAX_PRICE,
#    p.PRODUCT_NAME
#FROM FOOD_PRODUCT p
#GROUP BY p.CATEGORY
#HAVING p.CATEGORY IN ('과자','국','김치','식용유')
#ORDER BY p.PRICE DESC
#;
#SELECT
#    p.CATEGORY,
#    MAX(p.PRICE)
#FROM FOOD_PRODUCT p
#GROUP BY p.CATEGORY
#HAVING p.CATEGORY IN ('과자','국','김치','식용유')
#ORDER BY p.PRICE DESC
#;
#SELECT *
#FROM FOOD_PRODUCT